### ISSUE TITLE
Bug in UCPD_InitStruct() function

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeH5#7]
[UCPD_InitStruct()](https://github.com/STMicroelectronics/STM32CubeH5/blob/3d723b2467cdb13c2d780ceaa583b269680b67a4/Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_ucpd.c#L131) function is missing value lshift
is:
`UCPD_InitStruct->psc_ucpdclk`
should be:
`(UCPD_InitStruct->psc_ucpdclk << UCPD_CFG1_PSC_UCPDCLK_Pos)`
since UCPD_CFG1_PSC_UCPDCLK_Pos != 0

Btw, **PSC_UCPDCLK** name is inconsistent with registry description ([RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf) section 74.8.1) - see https://github.com/STMicroelectronics/cmsis_device_u5/issues/1

**Comment by ALABSTM** [comment]
Hi @tdjastrzebski,

Thank you for this report. From what I see, there is no need to shift the value of  `UCPD_InitStruct->psc_ucpdclk` before the assignment.

Indeed, the possible [values](https://github.com/STMicroelectronics/STM32CubeH5/blob/3d723b2467cdb13c2d780ceaa583b269680b67a4/Drivers/STM32H5xx_HAL_Driver/Inc/stm32h5xx_ll_ucpd.h#L225-L232) taken by `UCPD_InitStruct->psc_ucpdclk` are **already shifted**.

This is not the case for the other attributes like `UCPD_InitStruct->transwin` that are meant to take [values](https://github.com/STMicroelectronics/STM32CubeH5/blob/3d723b2467cdb13c2d780ceaa583b269680b67a4/Drivers/STM32H5xx_HAL_Driver/Inc/stm32h5xx_ll_ucpd.h#L60-L63) "between Min_Data=0x1 and Max_Data=0x1F" that are **not shifted**, thus **requiring the shift** operations.

I hope this makes things clearer. Please allow me to close this issue in this case.

With regards,
